# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never  # Use either pager or externalDiffCommand.
    # externalDiffCommand: difft --color=always --syntax-highlight=off  # Use either pager or externalDiffCommand.
  autoForwardBranches: allBranches

customCommands:
  - key: 'C'
    context: 'files'
    command: "git commit --verbose"
    output: terminal
  - key: 'b'
    command: 'git pull --rebase --autostash'
    context: 'localBranches'
    output: log
